chore: using zip deploy

diff --git a/.github/workflows/deploy-function-app.yml b/.github/workflows/deploy-function-app.yml
--- a/.github/workflows/deploy-function-app.yml
+++ b/.github/workflows/deploy-function-app.yml
@@ -69,11 +69,32 @@ jobs:
             environment=${{ inputs.environment }}
             location=${{ inputs.location }}
             
-      - name: "Deploy Azure Function App"
-        uses: azure/webapps-deploy@v2
-        with:
-          app-name: 'cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }}'
-          package: ${{ inputs.versionNumber }}            
+      - name: Create zipped function app package
+        run: |
+          cd ${{ inputs.versionNumber }}
+          zip -r ../functionapp.zip .
+          cd ..
+    
+      - name: Verify function app package exists
+        run: |
+          if [ ! -f "functionapp.zip" ]; then
+            echo "❌ functionapp.zip not found!"
+            exit 1
+          fi
+    
+      - name: Deploy using Zip Deploy
+        run: |
+          az functionapp deployment source config-zip \
+          --resource-group cchat-rg-${{ inputs.applicationName }}-${{ inputs.environment }} \
+          --name cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }} \
+          --src functionapp.zip
+            
+            
+#      - name: "Deploy Azure Function App"
+#        uses: azure/webapps-deploy@v2
+#        with:
+#          app-name: 'cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }}'
+#          package: ${{ inputs.versionNumber }}            
             
 #      - name: Zip function output
 #        run: |
